language: cpp
sudo: required
services:
    - docker
dist: trusty
os: linux
env:
    - JOB=lint
    - JOB=cibuild
    - JOB=citest_basic
    - JOB=citest_map
    - JOB=citest_dreamview
    - JOB=citest_perception
cache:
  directories:
  - $HOME/.cache/bazel
install: skip
before_script:
    - cp scripts/AGREEMENT.txt ${HOME}/.apollo_agreement.txt
script:
    - ./docker/scripts/dev_start.sh -t dev-x86_64-20180906_2002-ci
    - ./apollo_docker.sh ${JOB}
    - rm -rf "${HOME}/.cache/bazel/_bazel_${USER}/install"
notifications:
    email:
        on_success: change
        on_failure: always
